# Generated by Django 3.2.8 on 2021-10-12 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tshirt_name', models.CharField(max_length=100)),
                ('tshirt_Desc', models.CharField(blank=True, max_length=100, null=True)),
                ('discount', models.IntegerField()),
                ('tshirt_img', models.ImageField(upload_to='upload/img')),
                ('tshirt_img2', models.ImageField(null=True, upload_to='upload/img')),
                ('tshirt_img3', models.ImageField(null=True, upload_to='upload/img')),
                ('Ideal_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.idealfor')),
                ('Neck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.necktype')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.color')),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.occasion')),
                ('sleeve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.sleeve')),
            ],
        ),
    ]
