# Generated by Django 3.2.8 on 2021-10-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_sizevariant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizevariant',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='tshirt_img2',
            field=models.ImageField(blank=True, null=True, upload_to='upload/img'),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='tshirt_img3',
            field=models.ImageField(blank=True, null=True, upload_to='upload/img'),
        ),
    ]
