# Generated by Django 3.2.8 on 2021-11-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='add_to_home_page',
            field=models.BooleanField(default=True),
        ),
    ]
