# Generated by Django 3.2.8 on 2021-11-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_tshirt_add_to_home_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirt',
            name='add_to_home_page',
        ),
        migrations.AddField(
            model_name='tshirt',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
