# Generated by Django 3.2.8 on 2021-11-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_auto_20211115_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
