# Generated by Django 3.2.8 on 2021-11-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_rename_status_tshirt_add_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='Show_Slider',
            field=models.BooleanField(default=True),
        ),
    ]
