# Generated by Django 3.2.9 on 2021-11-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_slider_show_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='slug',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
