# Generated by Django 3.2.9 on 2021-11-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
