# Generated by Django 3.2.9 on 2021-12-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_alter_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirt',
            name='Add_Home_Page',
        ),
    ]
